title : Hansen Fang Portfolio
tagline: Site Tagline
author :
  name : Hansen Fang
  email : hansen@gmail.com
  github : hansen0730


markdown: rdiscount
pygments: true
permalink: /:year/:month/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "notes.txt"]
auto: true


# don't forget to separately set Google Analytics and Facebook Comments
# alternately, use Tumblr to post
